name: test

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      KUBECONTENT:
        required: true
jobs:
  deployment:
    if: ${{ startsWith(github.ref, 'refs/heads/deployment/') || github.ref == 'refs/heads/main'  }}
    runs-on: [self-hosted]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.9.0'

      - name: install dependencies
        run: npm install
        
      - name: build
        run: npm run build

      - name: Get version
        id: version
        run: |
          if [[ -n "$GITHUB_REF" && "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "tag version"
            echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
          else
            echo "commit version"    
            echo "::set-output name=version::${{ github.sha }}"
          fi

      - name: Build and push
        run: |
          docker login -u  ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t gitdatateam/retrievalplanet-club:${{ steps.version.outputs.version }} . 
          docker push gitdatateam/retrievalplanet-club:${{ steps.version.outputs.version }}

          docker tag gitdatateam/retrievalplanet-club:${{ steps.version.outputs.version }} gitdatateam/retrievalplanet-club:latest
          docker push gitdatateam/retrievalplanet-club:latest
        
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade retrievalplanet-club --install ./chart --namespace website --set-string tag=latest
          kubeconfig: ${{ secrets.KUBECONTENT }}
          overrule_existing_kubeconfig: "true"
